{
 "title": "Client Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "TCP Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tcp_connections_total" },
    { "expr": "tcp_recvs_kb" },
    { "expr": "tcp_sends_kb" }
   ]
  },
  {
   "title": "Read/write to the data-dir (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dir_reads_total" },
    { "expr": "dir_writes_total" }
   ]
  },
  {
   "title": "Read/write to the data-dir (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dir_reads_kb * 1024" },
    { "expr": "dir_writes_kb * 1024" }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "syscalls_failure_rate" }
   ]
  },
  {
   "title": "log10(Number of System Calls)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "log10(failed_syscalls_total)" }
   ]
  },
  {
   "title": "Rate of System Calls",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(failed_syscalls_total[30s])"
    }
   ]
  },
  {
   "title": "log10(Total Execution Time of Syscalls)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "log10(failed_syscalls_latency_total)"
    }
   ]
  },
  {
   "title": "Rate of Latencies",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(failed_syscalls_latency_total[30s])"
    }
   ]
  }
 ]
}