#!/usr/bin/with-contenv sh

echo "system call monitor started"

if strace -h | grep stack > /dev/null; then
  strace -qqq -ttt -T -Z -k -f --trace=%file,%memory,%net -p $(pidof java)
else
  strace -qqq -ttt -T -Z -f --trace=%file,%memory,%net -p $(pidof java)
fi