{
 "title": "Monitoring the monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=~\"se.kth.chaosorca.*\"}[30s]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{name=~\"se.kth.chaosorca.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{name=~\"se.kth.chaosorca.*\"}[30s]))",
     "legendFormat": "{{name}}-receive"
    },
    {
     "expr": "-sum by (name) (rate(container_network_transmit_bytes_total{name=~\"se.kth.chaosorca.*\"}[30s]))",
     "legendFormat": "{{name}}-transmit"
    }
   ]
  }
 ]
}