{
 "title": "Syscall Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Failure Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "syscalls_failure_rate" }
   ]
  },
  {
   "title": "log10(Number of System Calls)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "log10(failed_syscalls_total)" }
   ]
  },
  {
   "title": "Rate of System Calls",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(failed_syscalls_total[30s])"
    }
   ]
  },
  {
   "title": "log10(Total Execution Time of Syscalls)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "log10(failed_syscalls_latency_total)"
    }
   ]
  },
  {
   "title": "Rate of Latencies",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(failed_syscalls_latency_total[30s])"
    }
   ]
  }
 ]
}